project_id = "uugvnhmtmfiplpqcrxjg"

[functions.payments-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.generate-budget]
verify_jwt = false

[functions.lavadero-chat]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false
